### ISSUE TITLE
[FEATURE] using the cached values is configurable

### ISSUE THREAD

**Issue by NoevilMe** [jenkinsci/rest-list-parameter-plugin#17]
**Is your feature request related to a problem? Please describe.**
Actually, I need the latest rest api response in every build job. Not a cached value.
I think it's better to provide an option.

**Describe the solution you'd like**
A checkbox in configure page.

**Describe alternatives you've considered**
If the checkbox is checked, use the cached values, or retrieve values every time.

**Additional context**
None

**Comment by h1dden-da3m0n** [comment]
Hi there, and thank you for the feature request!
TBH I was playing with the thought of adding this, even before 1.0. It would even be  neatly supported by OKHttp, so I would not have to write much custom code. (unfortunately for that OKHttp needs a folder/file location on the host and I am unsure how to handle that from a Jenkins plugin perspective yet)

Regarless, I'll be a bit busy in the next couple of weeks, so unsure when I have time to work on this. If you yourself or anyone passing by wants to start earlier you are welcome to do so (just post here that u are working on it).
Otherwise, best I can do for now is to state that I will investigate once I find the time and label this as "soon:tm:".

**Comment by NoevilMe** [comment]
Thanks for your quick reply.  I'm not familiar with java code and jenkins plugins development. so I just modified the code and built it locally. But I can take a try when I have time.

**Comment by h1dden-da3m0n** [comment]
Hey, Noevi. Feel free to give it a try if you can.
Otherwise, if you don't mind waiting a week or two, I then should have some time again 🤞 .

**Comment by h1dden-da3m0n** [comment]
Small update: 
I found out how I could handle the file requirement for OkHttp's own builtin caching to work (thanks to the custom-folder-icon-plugin :grin: ).
Sadly I am pretty brain dead rn so, I'll give this method a try most likely next week, assuming I can fit in the time.
Thank you for offering to jump in :+1: , but unless you want this feature now I think I can fit this in next week (now that I have an idea to go of).

**Comment by NoevilMe** [comment]
It isn't an urgent requirement. Thanks very much.

**Comment by h1dden-da3m0n** [comment]
So, caching is in with 1.2.x. I hope it works as you have requested it and per default it will force web requests.
