### ISSUE TITLE
[BUG] Get error, A problem occurred while processing the request!

### ISSUE THREAD

**Issue by lpnueg4** [jenkinsci/rest-list-parameter-plugin#46]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16138783/107469364-90053100-6ba4-11eb-8c72-4dba81289bac.png)

**Versions (please complete the following information):**
 - Jenkins: [e.g. 2.249.1]
 - Plugin: [e.g. 1.0.0]
 - Browser [e.g. firefox, chrome]

**Additional context**

**Comment by h1dden-da3m0n** [comment]
Hi @lpnueg4,

sorry for the delayed response, work has kept me busy lately.
However, just posting a screenshot in the prepared Bug-Report template is not enough context to even start analysis on what may  be happening here :confused:.

Please provide more context such as:
* [ ] Jenkins version
* [ ] Plugin version
* [ ] browser used
* [ ] configuration (omit any sensitive URL or information) 
* [ ] if you can provide a excerpt of the Jenkins Logs

Since this really is nothing but a screenshot in the bug-template I will give you 2 days to provide more context.
Otherwise I have to close this bug report unfortunately, since I have nothing to base any analysis of.

**Comment by h1dden-da3m0n** [comment]
Okay, since there has been no update with information I could go of to track down the here reported bug by I will close this issue for now.
However, if more information gets provided on a later date I will re-open this issue.
